<a href="https://colab.research.google.com/github/NataliaTerreno/DataScience/blob/main/5_LIBRERIAS_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerías

**¿Qué es una librería?**

Una librería (o módulo) en Python es un conjunto de funciones, clases y herramientas ya escritas por otros desarrolladores, que podés importar y reutilizar en tus propios programas.

En lugar de escribir todo desde cero, usás librerías para:

 - Ahorrar tiempo.

- Evitar errores.

- Trabajar con herramientas optimizadas y probadas.

**¿Por qué son importantes las librerías?**

Python se volvió el lenguaje más usado en análisis de datos y ciencia de datos gracias a sus librerías especializadas, que permiten:

- Cargar y procesar grandes volúmenes de datos.

- Realizar cálculos numéricos complejos.

- Crear visualizaciones.

- Entrenar modelos de machine learning.

- Automatizar reportes.

## Principales librerías

### 1️⃣ NumPy – Cálculo numérico

🔹 Significa: Numerical Python

🔹 Para qué sirve: trabajar con arrays (vectores y matrices) y realizar cálculos matemáticos de forma eficiente.

🔹 Ventaja: reemplaza los bucles por operaciones vectorizadas (mucho más rápidas).

Usos empresariales:

- Análisis de márgenes, promedios y tendencias numéricas.

- Cálculos de rentabilidad, ROI, etc.

### 2️⃣ Pandas – Análisis y manipulación de datos

🔹 Construida sobre NumPy.

🔹 Permite trabajar con Series (una columna) y DataFrames (tablas completas).

🔹 Ideal para cargar, limpiar y analizar datos desde archivos Excel, CSV, bases de datos, etc.

Usos empresariales:

- Análisis de ventas, clientes, costos y beneficios.

- Preparar reportes y dashboards.

- Limpieza de datos antes del análisis.

### 3️⃣ Matplotlib – Gráficos básicos

🔹 Permite crear gráficos y visualizaciones de forma simple.

🔹 Base de muchas otras librerías gráficas (como Seaborn o Plotly).

Usos empresariales:

- Gráficos de evolución mensual.

- Comparaciones entre productos, regiones o equipos.

### 4️⃣ Seaborn – Visualizaciones estadísticas avanzadas

🔹 Basada en Matplotlib, pero más estética y con funciones automáticas.

🔹 Ideal para explorar relaciones entre variables.

Usos empresariales:

- Analizar correlaciones entre variables de negocio.

- Visualizar distribución de ingresos, clientes o precios.

### 5️⃣ Scikit-learn – Machine Learning

🔹 Librería para aplicar modelos predictivos y algoritmos de inteligencia artificial.

🔹 Usa NumPy y Pandas para manejar los datos.

Usos empresariales:

- Predicción de ventas.

- Segmentación de clientes.

- Análisis de riesgo o tendencias.

### 6️⃣ Statsmodels – Análisis estadístico

🔹 Complementa Pandas con modelos estadísticos y pruebas de hipótesis.

🔹 Muy usada en economía, finanzas y negocios.

Usos empresariales:

 - Análisis de series temporales.

- Evaluar impacto de estrategias comerciales.

- Modelos de regresión y correlación.

### 7️⃣ OpenPyXL / XlsxWriter – Manejo de Excel desde Python

🔹 Permiten crear o modificar archivos Excel automáticamente.

🔹 Ideal para reportes empresariales o exportar resultados.

# Numpay

Introducción a NumPy

- ¿Qué es NumPy?

Biblioteca fundamental de Python para cálculo numérico y arrays multidimensionales.

Es la base para muchas librerías de análisis y machine learning.

- ¿Qué es un array y diferencias con listas de Python

Lista de Python: estructura flexible, puede contener distintos tipos y es más lenta para operaciones numéricas element-wise.

Array de NumPy (ndarray): colección homogénea (mismo tipo), almacenada contiguamente en memoria; permite operaciones vectorizadas muy rápidas.

In [ ]:
# listas
a = [1, 2, 3]
b = [4, 5, 6]
# concatenación de listas
c = a + b # [1,2,3,4,5,6]
print(c)

# numpy arrays
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
# suma elemento a elemento (vectorizada)
C = A + B # array([5,7,9])
print(C)

[1, 2, 3, 4, 5, 6]
[5 7 9]


### Creación y manipulación de arrays en NumPy

In [ ]:
# Creación de arrays con np.array() → Sirve para convertir listas o tuplas en un array de NumPy.

import numpy as np

# Lista de ingresos por curso
ingresos = [10000, 15000, 13000]

# Convertir lista a array
arr = np.array(ingresos)

print(arr)        # [10000 15000 13000]
print(type(arr))  # <class 'numpy.ndarray'>

# El tipo ndarray (N-dimensional array) es la estructura base de NumPy.
# Puede ser de una dimensión (1D) o varias (2D, 3D, …).

[10000 15000 13000]
<class 'numpy.ndarray'>


In [ ]:
# Creación automática con np.arange() → Funciona como la función range() de Python, pero devuelve un array NumPy.
# Permite crear secuencias numéricas regulares.

# Sintaxis: np.arange(inicio, fin, paso)

# Fechas de lanzamiento de cursos (cada 2 meses)
meses = np.arange(0, 12, 2)
print(meses)
# [0 2 4 6 8 10]

[ 0  2  4  6  8 10]


In [ ]:
# Creación con np.linspace() → Crea un array con una cantidad específica de puntos dentro de un rango.
# Muy útil cuando necesitás valores espaciados uniformemente, por ejemplo, para gráficos o simulaciones.

# Sintaxis: np.linspace(inicio, fin, cantidad_puntos)

# Distribuir 5 precios entre 0 y 100
precios = np.linspace(0, 100, 5)
print(precios)
# [  0.  25.  50.  75. 100.]

[  0.  25.  50.  75. 100.]


In [ ]:
# Creación de arrays 2D → Podés crear matrices (arrays bidimensionales) con listas anidadas.

# Ingresos por curso y por mes (3 cursos x 4 meses)
ingresos_mensuales = np.array([
    [10000, 12000, 11000, 13000],
    [8000, 9500, 10000, 10500],
    [15000, 14000, 16000, 17000]
])

print(ingresos_mensuales)

[[10000 12000 11000 13000]
 [ 8000  9500 10000 10500]
 [15000 14000 16000 17000]]


In [ ]:
# Funciones rápidas para crear arrays comunes

a = np.zeros((2, 3))   # Matriz de ceros
b = np.ones((3, 3))    # Matriz de unos
c = np.eye(3)          # Matriz identidad
d = np.random.rand(2, 3)  # Números aleatorios entre 0 y 1

print("Matriz de ceros:\n", a)
print("\nMatriz de unos:\n", b)
print("\nMatriz identidad:\n", c)
print("\nMatriz aleatoria:\n", d)

Matriz de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Matriz de unos:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz aleatoria:
 [[0.74401343 0.90562381 0.2109737 ]
 [0.74055181 0.8447973  0.19882549]]


### Propiedades y formas

In [ ]:
arr = np.array([[10,20,30],[40,50,60]])

# arr.shape devuelve la tupla de dimensiones
a = arr.shape # (2, 3)
print(a)

# arr.dtype tipo de dato (float64, int64, etc.)
b = arr.dtype # dtype('int64')
print (b)

# arr.ndim número de dimensiones
c =arr.ndim # 2
print (c)

(2, 3)
int64
2


### Operaciones vectorizadas

Las operaciones entre arrays del mismo shape se aplican elemento a elemento y son muy rápidas.

Son una de las mayores ventajas de NumPy:
permiten aplicar una operación a todos los elementos del array al mismo tiempo, sin usar bucles for.

In [ ]:
import numpy as np

# Datos de ejemplo: precios y costos por curso
precios = np.array([100, 200, 300])
costos = np.array([10, 20, 30])

# Operaciones básicas
print("Suma (precios + costos):", precios + costos)
print("Resta (precios - costos):", precios - costos)
print("Multiplicación (precios * 2):", precios * 2)
print("División (precios / costos):", precios / costos)

# Cada operación se aplica elemento a elemento porque los arrays tienen la misma forma (shape) (3,)
# Si los arrays no tienen el mismo shape...NumPy intenta ampliar ("broadcast") uno de ellos para que las dimensiones coincidan automáticamente, si es posible. Si no es posible, lanza un error (ValueError: operands could not be broadcast together).

Suma (precios + costos): [110 220 330]
Resta (precios - costos): [ 90 180 270]
Multiplicación (precios * 2): [200 400 600]
División (precios / costos): [10. 10. 10.]


### Funciones matemáticas esenciales (mean, sum, max, min, sqrt, dot)

Estas funciones son vectorizadas, es decir, aplican operaciones a todos los elementos del array de forma rápida y eficiente, sin necesidad de bucles for.

In [ ]:
import numpy as np

# Crear un array de ejemplo
scores = np.array([80, 95, 70, 60])

# Promedio de los valores
print("Promedio (mean):", scores.mean())  # (80 + 95 + 70 + 60) / 4 = 76.25

# Suma total
print("Suma total (sum):", scores.sum())  # 305

# Valor máximo y mínimo
print("Máximo (max):", scores.max())  # 95
print("Mínimo (min):", scores.min())  # 60

# Raíz cuadrada elemento a elemento
print("Raíz cuadrada (sqrt):")
print(np.sqrt(scores))  # array con las raíces cuadradas de cada valor

# --------------------------------------------

# Producto punto (dot product)
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Cálculo del producto punto: 1*4 + 2*5 + 3*6 = 32
print("Producto punto (dot):", np.dot(v1, v2))

Promedio (mean): 76.25
Suma total (sum): 305
Máximo (max): 95
Mínimo (min): 60
Raíz cuadrada (sqrt):
[8.94427191 9.74679434 8.36660027 7.74596669]
Producto punto (dot): 32


### Indexación y slicing en arrays

In [ ]:
import numpy as np

# Crear un array 1D
arr = np.array([10, 20, 30, 40, 50])
print("Array original 1D:", arr)

# ---------------------------------------------
# Acceder a elementos individuales
print("\nAcceder al primer elemento (índice 0):", arr[0])   # 10
print("Acceder al último elemento (índice -1):", arr[-1])  # 50

# ---------------------------------------------
# Slicing (subconjuntos del array)
# Sintaxis: arr[start:stop:step]
print("\nSlicing de elementos 1 a 3:", arr[1:4])      # [20 30 40]
print("Cada dos elementos:", arr[::2])               # [10 30 50]
print("Del final hacia el inicio:", arr[::-1])       # [50 40 30 20 10]

# ---------------------------------------------
# Arrays 2D
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

print("\nArray 2D:")
print(arr2d)

# Acceder a un elemento (fila, columna)
print("\nElemento en fila 1, columna 2:", arr2d[1, 2])  # 60

# Slicing por filas y columnas
# Sintaxis: arr[row_start:row_stop, col_start:col_stop]
print("\nSubmatriz filas 0-1 y columnas 1-2:")
print(arr2d[0:2, 1:3])
# Resultado esperado:
# [[20 30]
#  [50 60]]

# ---------------------------------------------
# Indexación booleana y por máscaras
print("\nElementos mayores a 40:")
print(arr2d[arr2d > 40])  # Devuelve solo los valores que cumplen la condición


# Crear una máscara  →  array de valores booleanos (True o False) que indica qué elementos del array original cumplen una condición.
mask = arr2d % 20 == 0
print("\nMáscara de múltiplos de 20:")
print(mask)

print("\nElementos que cumplen la máscara (múltiplos de 20):")
print(arr2d[mask])

Array original 1D: [10 20 30 40 50]

Acceder al primer elemento (índice 0): 10
Acceder al último elemento (índice -1): 50

Slicing de elementos 1 a 3: [20 30 40]
Cada dos elementos: [10 30 50]
Del final hacia el inicio: [50 40 30 20 10]

Array 2D:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Elemento en fila 1, columna 2: 60

Submatriz filas 0-1 y columnas 1-2:
[[20 30]
 [50 60]]

Elementos mayores a 40:
[50 60 70 80 90]

Máscara de múltiplos de 20:
[[False  True False]
 [ True False  True]
 [False  True False]]

Elementos que cumplen la máscara (múltiplos de 20):
[20 40 60 80]


### Broadcasting

Broadcasting es el mecanismo que usa NumPy para realizar operaciones entre arrays de distintas formas (shapes),
“estirando” o “replicando” automáticamente uno de ellos sin copiar los datos.

Si las reglas se cumplen → la operación se hace elemento a elemento.

Si no → lanza un error.

Ventajas del Broadcasting

- Velocidad: no hace copias innecesarias de los datos.

- Simplicidad: evita escribir bucles.

- Memoria eficiente: reutiliza el mismo array más pequeño.

In [ ]:
# ======================================================
# Ejemplo 1 – Arrays con el mismo shape
# ======================================================
print("Ejemplo 1 – Mismo shape\n")

A = np.array([100, 200, 300])
B = np.array([10, 20, 30])

print("A:", A)
print("B:", B)
print("A + B =", A + B)  # Suma elemento a elemento
print("A * B =", A * B)  # Multiplicación elemento a elemento
print("-" * 50, "\n")


🔹 Ejemplo 1 – Mismo shape

A: [100 200 300]
B: [10 20 30]
A + B = [110 220 330]
A * B = [1000 4000 9000]
-------------------------------------------------- 



In [ ]:
# ======================================================
# Ejemplo 2 – Broadcasting con una fila (1D expandida a 2D)
# ======================================================
print("Ejemplo 2 – Broadcasting con filas\n")

A = np.array([[10, 20, 30],
              [40, 50, 60]])   # shape (2, 3)
B = np.array([1, 2, 3])        # shape (3,)

print("Shape de A:", A.shape)
print("Shape de B:", B.shape)
print("Resultado A + B =\n", A + B)  # B se "replica" en cada fila
print("-" * 50, "\n")

Ejemplo 2 – Broadcasting con filas

Shape de A: (2, 3)
Shape de B: (3,)
Resultado A + B =
 [[11 22 33]
 [41 52 63]]
-------------------------------------------------- 



In [ ]:
# ======================================================
# Ejemplo 3 – Broadcasting con columnas
# ======================================================
print("Ejemplo 3 – Broadcasting con columnas\n")

A = np.array([[10, 20, 30],
              [40, 50, 60]])   # shape (2, 3)
B = np.array([[1],
              [2]])            # shape (2, 1)

print("Shape de A:", A.shape)
print("Shape de B:", B.shape)
print("Resultado A * B =\n", A * B)  # Cada fila se multiplica por el valor de su fila en B
print("-" * 50, "\n")

Ejemplo 3 – Broadcasting con columnas

Shape de A: (2, 3)
Shape de B: (2, 1)
Resultado A * B =
 [[ 10  20  30]
 [ 80 100 120]]
-------------------------------------------------- 



In [ ]:
# ======================================================
# Ejemplo 4 – Broadcasting con escalar
# ======================================================
print("Ejemplo 4 – Broadcasting con escalar\n")

A = np.array([[1, 2, 3],
              [4, 5, 6]])
escalar = 10

print("A:\n", A)
print("Escalar:", escalar)
print("A + escalar =\n", A + escalar)  # El escalar se aplica a todos los elementos
print("-" * 50, "\n")



Ejemplo 4 – Broadcasting con escalar

A:
 [[1 2 3]
 [4 5 6]]
Escalar: 10
A + escalar =
 [[11 12 13]
 [14 15 16]]
-------------------------------------------------- 



In [ ]:
# ======================================================
# Ejemplo 5 – Broadcasting más complejo
# ======================================================
print("Ejemplo 5 – Broadcasting con diferentes shapes\n")

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])  # shape (3, 3)
B = np.array([1, 0, -1])    # shape (3,)

print("Shape de A:", A.shape)
print("Shape de B:", B.shape)
print("A + B =\n", A + B)  # B se suma a cada fila
print("-" * 50, "\n")

Ejemplo 5 – Broadcasting con diferentes shapes

Shape de A: (3, 3)
Shape de B: (3,)
A + B =
 [[2 2 2]
 [5 5 5]
 [8 8 8]]
-------------------------------------------------- 



In [ ]:
# ======================================================
# Ejemplo 6 – Broadcasting incompatible
# ======================================================
print("Ejemplo 6 – Error por shapes incompatibles\n")

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])   # shape (3, 2)
B = np.array([[10, 20, 30],
              [40, 50, 60]])  # shape (2, 3)

print("Shape de A:", A.shape)
print("Shape de B:", B.shape)

try:
    print(A + B)  # Error: shapes incompatibles (3,2) y (2,3)
except ValueError as e:
    print("Error de broadcasting:", e)
print("-" * 50, "\n")



Ejemplo 6 – Error por shapes incompatibles

Shape de A: (3, 2)
Shape de B: (2, 3)
Error de broadcasting: operands could not be broadcast together with shapes (3,2) (2,3) 
-------------------------------------------------- 



In [ ]:
# ======================================================
# Ejemplo 7 – Visualización conceptual de expansión
# ======================================================
print("Ejemplo 7 – Cómo NumPy expande internamente las dimensiones\n")

A = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)
B = np.array([10, 20, 30])  # shape (3,)

print("A:\n", A)
print("B:\n", B)
print("A + B =\n", A + B)
print("\nVisualmente, NumPy trata B como si fuera:\n[[10, 20, 30], [10, 20, 30]]\n")
print("-" * 50)

Ejemplo 7 – Cómo NumPy expande internamente las dimensiones

A:
 [[1 2 3]
 [4 5 6]]
B:
 [10 20 30]
A + B =
 [[11 22 33]
 [14 25 36]]

Visualmente, NumPy trata B como si fuera:
[[10, 20, 30], [10, 20, 30]]

--------------------------------------------------


### Buenas prácticas y rendimiento

- Preferir operaciones vectorizadas sobre loops Python para grandes volúmenes de datos.

- Evitar conversiones frecuentes entre listas y arrays.

- Cuidar tipos de datos (dtype) para memoria: usar float32 si la precisión float64 no es necesaria.

- Cuando trabajes con grandes datasets, usar np.memmap o herramientas como pandas y dask si superás la memoria.

# Pandas

Pandas es una librería de Python para análisis, limpieza y manipulación de datos.

Permite trabajar con estructuras tipo tabla (como Excel) de manera rápida y flexible.

Integración con otras librerías

- Pandas + NumPy: operaciones matemáticas avanzadas.

- Pandas + Matplotlib / Seaborn: visualización enriquecida.

- Pandas + Scikit-learn: preparación de datos para modelos ML.

- Pandas + SQLAlchemy: conexión con bases de datos SQL.

- Pandas + ExcelWriter: reportes automatizados.

Usos

- Facilita leer, limpiar y transformar datos de múltiples fuentes (CSV, Excel, SQL, JSON, etc.).

- Permite filtrar, agrupar, resumir y visualizar la información fácilmente.

- Es la base para preparar datasets antes de aplicar machine learning o análisis estadístico.

### Instalación y entorno de trabajo

Instalación (si trabajás localmente, ej jupyter):
pip install pandas

En Google Colab, Pandas ya viene preinstalado, por lo que no hace falta instalarlo manualmente

In [ ]:

# Convención estándar para importar >>> El alias pd es la forma más usada por la comunidad científica y profesional.

import pandas as pd

# Ver versión instalada
print(pd.__version__)

2.2.2


### Series

Una Series es la estructura unidimensional de Pandas (1D).
Podés pensarla como una columna de una hoja de cálculo o tabla, con dos componentes:

1.Valores: los datos reales (números, texto, fechas, etc.).

2.Índices: las etiquetas que identifican a cada valor.

Tiene índices (etiquetas) que identifican cada valor.

Admite distintos tipos de datos (int, float, string, etc.).

Permite aplicar operaciones vectorizadas (suma, promedio, etc.).

#### Creación de series

In [ ]:
# Desde una lista

import pandas as pd

serie = pd.Series([10, 20, 30, 40])
print(serie)

# Por defecto, Pandas asigna un índice numérico comenzando en 0.


0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
# Desde una lista con etiquetas personalizadas

serie = pd.Series([100, 200, 300], index=['Ene', 'Feb', 'Mar'])
serie

# si se usa print(serie) aparece formato plano, si no se usa print y solo se escribe serie, aparece tabla con formato

Ene    100
Feb    200
Mar    300
dtype: int64

In [ ]:
# Desde un diccionario

data = {'A': 10, 'B': 20, 'C': 30}
serie = pd.Series(data)
serie

# El diccionario convierte sus claves en índices y sus valores en datos.

A    10
B    20
C    30
dtype: int64

In [ ]:
# Desde un array de NumPy

import numpy as np

array = np.array([5, 10, 15, 20])
serie = pd.Series(array)
serie

0     5
1    10
2    15
3    20
dtype: int64

#### Atributos

In [ ]:
serie = pd.Series([10, 20, 30], index=['A', 'B', 'C'])

print("Valores:", serie.values)
print("Índices:", serie.index)
print("Tipo de datos:", serie.dtype)
print("Tamaño:", serie.shape)
print("Número de dimensiones:", serie.ndim)

Valores: [10 20 30]
Índices: Index(['A', 'B', 'C'], dtype='object')
Tipo de datos: int64
Tamaño: (3,)
Número de dimensiones: 1


#### Acceso a elementos

In [ ]:
# Por índice numérico (posición)

print(serie[0])  # Primer elemento
print("---------------------------------------")

# Por etiqueta

print(serie['B'])
print("---------------------------------------")

# Con métodos .iloc[] y .loc[]

   # iloc -> acceso por posición
print(serie.iloc[1])

   # loc -> acceso por etiqueta
print(serie.loc['C'])
print("---------------------------------------")

#Slicing

print(serie[:2])        # Primeros dos elementos
print(serie['A':'C'])   # Desde 'A' hasta 'C' (inclusive)

10
---------------------------------------
20
---------------------------------------
20
30
---------------------------------------
A    10
B    20
dtype: int64
A    10
B    20
C    30
dtype: int64


/tmp/ipython-input-825485661.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(serie[0])  # Primer elemento


#### Operaciones matemáticas y vectorizadas

In [ ]:
serie = pd.Series([10, 20, 30])
print("---------------------------------------")
print("Suma:", serie + 5)
print("---------------------------------------")
print("Multiplicación:", serie * 2)
print("---------------------------------------")
print("Raíz cuadrada:", serie ** 0.5)

---------------------------------------
Suma: 0    15
1    25
2    35
dtype: int64
---------------------------------------
Multiplicación: 0    20
1    40
2    60
dtype: int64
---------------------------------------
Raíz cuadrada: 0    3.162278
1    4.472136
2    5.477226
dtype: float64


#### Filtrado de datos ( aplicar condiciones lógicas directamente sobre la Series)

In [ ]:
serie = pd.Series([10, 25, 40, 15, 30])

print("Valores mayores a 20:")
print(serie[serie > 20])

Valores mayores a 20:
1    25
2    40
4    30
dtype: int64


#### Indexación booleana (máscara)

Este método es muy usado en limpieza de datos (por ejemplo, para eliminar valores nulos o atípicos).

In [ ]:
serie = pd.Series([5, 10, 15, 20])
mascara = serie > 10
print("Máscara booleana:")
print(mascara)

print("\nElementos que cumplen la condición:")
print(serie[mascara])

Máscara booleana:
0    False
1    False
2     True
3     True
dtype: bool

Elementos que cumplen la condición:
2    15
3    20
dtype: int64


#### Funciones

Podés aplicar funciones personalizadas a una Serie usando .apply() o funciones lambda.

In [ ]:
serie = pd.Series([10, 20, 30])

# Función personalizada
def convertir_usd(valor):
    return valor * 1000

print(serie.apply(convertir_usd))

# Con lambda
print(serie.apply(lambda x: x * 1.21))  # ejemplo de aplicar IVA

0    10000
1    20000
2    30000
dtype: int64
0    12.1
1    24.2
2    36.3
dtype: float64


#### Operaciones con dos series

Cuando sumás o combinás dos Series, Pandas alinea los índices automáticamente.
Si los índices no coinciden, Pandas devuelve NaN (valor faltante) en las posiciones sin correspondencia.

In [ ]:
serie1 = pd.Series([10, 20, 30], index=['A', 'B', 'C'])
serie2 = pd.Series([5, 15, 25], index=['B', 'C', 'D'])

print(serie1 + serie2)

A     NaN
B    25.0
C    45.0
D     NaN
dtype: float64


#### Valores nulos y ausentes

Pandas usa NaN (Not a Number) para representar datos faltantes.

In [ ]:
serie = pd.Series([10, None, 30, None, 50])

print("Serie original:")
print(serie)

print("\nVerificar nulos:")
print(serie.isnull())

print("\nReemplazar nulos:")
print(serie.fillna(0))

print("\nEliminar nulos:")
print(serie.dropna())

Serie original:
0    10.0
1     NaN
2    30.0
3     NaN
4    50.0
dtype: float64

Verificar nulos:
0    False
1     True
2    False
3     True
4    False
dtype: bool

Reemplazar nulos:
0    10.0
1     0.0
2    30.0
3     0.0
4    50.0
dtype: float64

Eliminar nulos:
0    10.0
2    30.0
4    50.0
dtype: float64


#### Métodos adicionales útiles

In [ ]:
serie = pd.Series(['rojo', 'azul', 'rojo', 'verde', 'azul'])

print("Valores únicos:", serie.unique())
print("Frecuencia de cada valor:")
print(serie.value_counts())
print("Ordenada alfabéticamente:")
print(serie.sort_values())

Valores únicos: ['rojo' 'azul' 'verde']
Frecuencia de cada valor:
rojo     2
azul     2
verde    1
Name: count, dtype: int64
Ordenada alfabéticamente:
1     azul
4     azul
0     rojo
2     rojo
3    verde
dtype: object


### Dataframe

→ Es la estructura principal de Pandas: una tabla con filas y columnas.

→ Cada columna es una Series.

→ Tiene nombres de columnas y etiquetas de fila.

  → Permite cálculos, filtrado, agrupamiento y combinaciones.


#### Creación y lectura



In [ ]:
# Desde diccionarios de listas (el caso más común)

import pandas as pd

data = {
    "alumno": ["Ana", "Luis", "María", "Juan"],
    "curso": ["Marketing", "Finanzas", "Marketing", "Data Science"],
    "precio": [20000, 25000, 20000, 30000],
    "estado": ["completado", "en progreso", "completado", "pendiente"]
}

df = pd.DataFrame(data)
df

alumno         curso  precio       estado
0    Ana     Marketing   20000   completado
1   Luis      Finanzas   25000  en progreso
2  María     Marketing   20000   completado
3   Juan  Data Science   30000    pendiente

In [ ]:
# Desde listas de diccionarios

data = [
    {"alumno": "Ana", "curso": "Marketing", "precio": 20000},
    {"alumno": "Luis", "curso": "Finanzas", "precio": 25000},
    {"alumno": "María", "curso": "Marketing", "precio": 20000},
]

df = pd.DataFrame(data)
df

alumno      curso  precio
0    Ana  Marketing   20000
1   Luis   Finanzas   25000
2  María  Marketing   20000

In [ ]:
# Desde arrays de NumPy

import numpy as np

arr = np.array([
    [1, "Marketing", 20000],
    [2, "Finanzas", 25000],
    [3, "Data Science", 30000]
])

df = pd.DataFrame(arr, columns=["id", "curso", "precio"])
df

id         curso precio
0  1     Marketing  20000
1  2      Finanzas  25000
2  3  Data Science  30000

Desde archivos externos

→ CSV
df = pd.read_csv("ventas_cursos.csv")

→ Excel
df = pd.read_excel("ventas_cursos.xlsx")

→ JSON : API de facturación o CRM → JSON.

df = pd.read_json("alumnos.json")

→ Drive

FORMA 1 — Desde URL pública/exportable (más simple)

No necesitás instalar nada si el archivo tiene permisos “cualquiera con el enlace puede ver”.

1. Copiás el ID del Google Sheet
2. Cargás el Google Sheet como CSV

FORMA 2 — Usar el archivo dentro de tu Drive (sin hacerlo público)
1. Montás Google Drive
2. Usás gspread para conectarte a Sheets directamente

FORMA 3 — Acceder a un Google Sheet compartido (requiere compartirlo con tu cuenta de servicio)

Si el archivo está en una carpeta compartida:

Ejecutás la celda para ver tu “service account email”.

Compartís el Google Sheet con ese email.

Luego lo cargás como en el método 2.

In [ ]:
# Ejemplo FORMA 2: Abrir dataframe desde drive

import gspread
import pandas as pd
from google.colab import auth
from google.auth import default # Import default from google.auth

# Autorización
auth.authenticate_user()

creds, project = default() # Get credentials and project from google.auth.default()
gc = gspread.authorize(creds) # Use creds for authorization

# Abrir Google Sheet por nombre
worksheet = gc.open("df_cursos").sheet1

# Convertir a DataFrame
data = worksheet.get_all_records()
df = pd.DataFrame(data)

df.head()

# Si actualizo el Google Sheets y doy ejecutar de nuevo, se actualiza acá

id_venta       fecha         curso   categoria precio cantidad  region  \
0         1  2024-01-03     Marketing   Marketing  20000        1   Norte   
1         2  2024-01-05      Finanzas    Finanzas  25000        1   Norte   
2         3  2024-01-08  data science  Tecnología  30000        1     Sur   
3         4  2024-01-09  Data Science  tecnología  30000        2     Sur   
4         5  2024-01-15     Liderazgo   Liderazgo  28000        1  Centro   

  vendedor estado_pago  
0      Ana      Pagado  
1     Luis   Pendiente  
2      Ana      Pagado  
3      Ana      Pagado  
4    Sofía      Pagado

Parámetros de lectura

1) sep: Cuando tu archivo no está separado por comas. No todos los CSV usan coma: algunos usan punto y coma, tabulador, barra vertical, etc.

df = pd.read_csv("ventas.csv", sep=";")

2) header: Cuando tu archivo tiene o no tiene nombres de columnas en la primera fila. Pandas necesita saber dónde están los nombres de las columnas.

df = pd.read_csv("ventas.csv", header=None)

df = pd.read_csv("ventas.csv", header=1)
*Archivo donde el encabezado está en otra fila (por ejemplo fila 2):

3) names: Cuando querés asignar tus propios nombres de columnas porque el archivo no tiene encabezados, Los encabezados vienen feos o incompletos, Querés estandarizarlos

cols = ["id_venta", "fecha", "curso", "precio"]

df = pd.read_csv("ventas.csv", names=cols, header=None)

4) index_col: Cuando querés que una columna funcione como índice del DataFrame.

df = pd.read_csv("ventas.csv", index_col="id_venta")

5) usecols: Cuando solo necesitás leer algunas columnas, no todas.

df = pd.read_csv("ventas.csv", usecols=["curso", "precio"])

6) na_values:
Cuando en tu archivo los valores nulos aparecen como texto, por ejemplo: NULL".
"N/A", "Sin dato", "No asignado"

df = pd.read_csv("ventas.csv", na_values=["NULL"])
* Para convertir "NULL" a NaN

7) encoding: Cuando el archivo tiene acentos, ñ, caracteres especiales y te da error al abrirlo. Los CSV de sistemas, exportaciones o Windows a veces vienen con codificación distinta: UTF-8, ISO-8859-1, latin1

df = pd.read_csv("ventas.csv", encoding="latin1")

#### Exploración inicial de datos

In [ ]:
# .head() — primeras filas

df.head()

id_venta       fecha         curso   categoria precio cantidad  region  \
0         1  2024-01-03     Marketing   Marketing  20000        1   Norte   
1         2  2024-01-05      Finanzas    Finanzas  25000        1   Norte   
2         3  2024-01-08  data science  Tecnología  30000        1     Sur   
3         4  2024-01-09  Data Science  tecnología  30000        2     Sur   
4         5  2024-01-15     Liderazgo   Liderazgo  28000        1  Centro   

  vendedor estado_pago  
0      Ana      Pagado  
1     Luis   Pendiente  
2      Ana      Pagado  
3      Ana      Pagado  
4    Sofía      Pagado

In [ ]:
# .tail() — últimas filas

df.tail()

id_venta       fecha                curso   categoria precio cantidad  \
35        36  2024-04-10  Excel para Negocios  Tecnología  18000        1   
36        37  2024-04-12                 RRHH        RRHH  22000        1   
37        38  2024-04-12                 rrhh        rrhh  22000        1   
38        39  2024-04-15       Emprendimiento    Negocios  23000        1   
39        40  2024-04-15       emprendimiento    negocios  23000        1   

    region vendedor estado_pago  
35     Sur      Ana      Pagado  
36   Norte    Sofía      Pagado  
37   Norte    Sofía      Pagado  
38  Centro    Pedro      Pagado  
39  Centro    Pedro      Pagado

In [ ]:
# .info() — tipos de datos, nulos, memoria

df.info()

# Te permite detectar: columnas numéricas cargadas como texto, fechas no convertidas, muchos valores faltantes, errores del archivo original

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   id_venta     40 non-null     int64 
 1   fecha        40 non-null     object
 2   curso        40 non-null     object
 3   categoria    40 non-null     object
 4   precio       40 non-null     object
 5   cantidad     40 non-null     object
 6   region       40 non-null     object
 7   vendedor     40 non-null     object
 8   estado_pago  40 non-null     object
dtypes: int64(1), object(8)
memory usage: 2.9+ KB


In [ ]:
# .describe() — estadísticas básicas

df.describe()

id_venta        precio
count  40.000000     39.000000
mean   20.500000  23769.230769
std    11.690452   5203.549085
min     1.000000  15000.000000
25%    10.750000  20500.000000
50%    20.500000  23000.000000
75%    30.250000  28000.000000
max    40.000000  35000.000000

In [ ]:
# .describe() — estadísticas básicas

df["precio"] = pd.to_numeric(df["precio"], errors="coerce")

# Convierte todo a número
# Si encuentra algo que no es número (por ejemplo "NULL"), lo convierte a NaN
# Ahorra sí .describe() funciona correctamente para la columna precio

In [ ]:
df['precio'].describe()

count       39.000000
mean     23769.230769
std       5203.549085
min      15000.000000
25%      20500.000000
50%      23000.000000
75%      28000.000000
max      35000.000000
Name: precio, dtype: float64

In [ ]:
# .shape — tamaño del dataset

df.shape   # (filas, columnas)

(40, 9)

In [ ]:
# .columns — nombres de columnas

df.columns


Index(['id_venta', 'fecha', 'curso', 'categoria', 'precio', 'cantidad',
       'region', 'vendedor', 'estado_pago'],
      dtype='object')

In [ ]:
# .index — índice actual

df.index


RangeIndex(start=0, stop=40, step=1)

#### Tipos de datos y conversión

In [ ]:
# Ver tipos
df.dtypes

id_venta                int64
fecha          datetime64[ns]
curso                  object
categoria              object
precio                float64
cantidad               object
region                 object
vendedor               object
estado_pago          category
dtype: object

In [ ]:
# Convertir precio a número
df["precio"] = df["precio"].astype(float)

In [ ]:
# Convertir fecha
df["fecha"] = pd.to_datetime(df["fecha"])

In [ ]:
# Convertir estados a categorías

df["estado_pago"] = df["estado_pago"].astype("category")

#### Selección y acceso a datos

In [ ]:
# selección de columna
df["precio"].head()

0    20000.0
1    25000.0
2    30000.0
3    30000.0
4    28000.0
Name: precio, dtype: float64

In [ ]:
# selección de 2 o mas columnas
df[["precio", "estado_pago"]].head()

precio estado_pago
0  20000.0      Pagado
1  25000.0   Pendiente
2  30000.0      Pagado
3  30000.0      Pagado
4  28000.0      Pagado

In [ ]:
# Selección de fila

# .iloc[] (por posición numérica)
df.iloc[0]

id_venta                         1
fecha          2024-01-03 00:00:00
curso                    Marketing
categoria                Marketing
precio                     20000.0
cantidad                         1
region                       Norte
vendedor                       Ana
estado_pago                 Pagado
Name: 0, dtype: object

In [ ]:
# Selección de fila

# .loc[] (por etiqueta del índice)
df.loc[df["vendedor"] == "Ana"]

id_venta      fecha                  curso     categoria   precio  \
0          1 2024-01-03              Marketing     Marketing  20000.0   
2          3 2024-01-08           data science    Tecnología  30000.0   
3          4 2024-01-09           Data Science    tecnología  30000.0   
7          8 2024-02-01    Excel para negocios    Tecnología  18000.0   
12        13 2024-02-15  Comunicación efectiva  Comunicación  16000.0   
13        14 2024-02-15  Comunicación Efectiva  comunicación  16000.0   
22        23 2024-03-15             google ads     Marketing  23000.0   
23        24 2024-03-15             Google Ads     marketing  23000.0   
29        30 2024-03-29              Liderazgo     Liderazgo  28000.0   
35        36 2024-04-10    Excel para Negocios    Tecnología  18000.0   

   cantidad region vendedor estado_pago  
0         1  Norte      Ana      Pagado  
2         1    Sur      Ana      Pagado  
3         2    Sur      Ana      Pagado  
7         1  Norte      Ana      Pagado  
12        1    Sur      Ana      Pagado  
13        1    Sur      Ana      Pagado  
22        1  Norte      Ana      Pagado  
23        1  Norte      Ana      Pagado  
29        1    Sur      Ana   Pendiente  
35        1    Sur      Ana      Pagado

In [ ]:
# Slicing

df[0:3]   # filas de 0 a 2

id_venta      fecha         curso   categoria   precio cantidad region  \
0         1 2024-01-03     Marketing   Marketing  20000.0        1  Norte   
1         2 2024-01-05      Finanzas    Finanzas  25000.0        1  Norte   
2         3 2024-01-08  data science  Tecnología  30000.0        1    Sur   

  vendedor estado_pago  
0      Ana      Pagado  
1     Luis   Pendiente  
2      Ana      Pagado

In [ ]:
# Condiciones

df[(df["precio"] > 20000) & (df["estado_pago"] == "Pagado")]

id_venta      fecha                    curso   categoria   precio  \
2          3 2024-01-08             data science  Tecnología  30000.0   
3          4 2024-01-09             Data Science  tecnología  30000.0   
4          5 2024-01-15                Liderazgo   Liderazgo  28000.0   
5          6 2024-01-22                   Ventas      Ventas  21000.0   
6          7 2024-01-22                   ventas      ventas  21000.0   
11        12 2024-02-12         Recursos Humanos        RRHH  22000.0   
14        15 2024-02-20              Negociación      Ventas  24000.0   
16        17 2024-03-05   Estrategia Empresarial    Negocios  35000.0   
21        22 2024-03-13                      SEO   Marketing  25000.0   
22        23 2024-03-15               google ads   Marketing  23000.0   
23        24 2024-03-15               Google Ads   marketing  23000.0   
24        25 2024-03-20   Transformación Digital  Tecnología  33000.0   
25        26 2024-03-21                OKR y KPI  Tecnología  31000.0   
26        27 2024-03-22  Inteligencia Artificial  Tecnología  34000.0   
27        28 2024-03-25      Análisis de Mercado    Negocios  28000.0   
28        29 2024-03-28      análisis de mercado    NEGOCIOS  28000.0   
30        31 2024-04-01                   Ventas      Ventas  21000.0   
31        32 2024-04-01                   Ventas      Ventas  21000.0   
32        33 2024-04-02             Data Science  Tecnología  30000.0   
33        34 2024-04-05                 Power BI  Tecnología  27000.0   
36        37 2024-04-12                     RRHH        RRHH  22000.0   
37        38 2024-04-12                     rrhh        rrhh  22000.0   
38        39 2024-04-15           Emprendimiento    Negocios  23000.0   
39        40 2024-04-15           emprendimiento    negocios  23000.0   

   cantidad  region vendedor estado_pago  
2         1     Sur      Ana      Pagado  
3         2     Sur      Ana      Pagado  
4         1  Centro    Sofía      Pagado  
5         3    Cuyo     Luis      Pagado  
6         2    Cuyo     Luis      Pagado  
11        1   Norte    Sofía      Pagado  
14        1    Cuyo     Luis      Pagado  
16        1     Sur     Lara      Pagado  
21        1     Sur     Lara      Pagado  
22        1   Norte      Ana      Pagado  
23        1   Norte      Ana      Pagado  
24        1    Cuyo     Luis      Pagado  
25        1  Centro    Pedro      Pagado  
26        1     Sur     Lara      Pagado  
27        1   Norte    Sofía      Pagado  
28        2   Norte    Sofía      Pagado  
30        1    Cuyo     Luis      Pagado  
31        1    Cuyo     Luis      Pagado  
32        1     Sur     Lara      Pagado  
33        1  Centro    Pedro      Pagado  
36        1   Norte    Sofía      Pagado  
37        1   Norte    Sofía      Pagado  
38        1  Centro    Pedro      Pagado  
39        1  Centro    Pedro      Pagado

#### Data Cleaning (limpieza y preparación de datos)

In [ ]:
# Ver valores nulos

df.isnull()

id_venta  fecha  curso  categoria  precio  cantidad  region  vendedor  \
0      False  False  False      False   False     False   False     False   
1      False  False  False      False   False     False   False     False   
2      False  False  False      False   False     False   False     False   
3      False  False  False      False   False     False   False     False   
4      False  False  False      False   False     False   False     False   
5      False  False  False      False   False     False   False     False   
6      False  False  False      False   False     False   False     False   
7      False  False  False      False   False     False   False     False   
8      False  False  False      False   False     False   False     False   
9      False  False  False      False   False     False   False     False   
10     False  False  False      False    True     False   False     False   
11     False  False  False      False   False     False   False     False   
12     False  False  False      False   False     False   False     False   
13     False  False  False      False   False     False   False     False   
14     False  False  False      False   False     False   False     False   
15     False  False  False      False   False     False   False     False   
16     False  False  False      False   False     False   False     False   
17     False  False  False      False   False     False   False     False   
18     False  False  False      False   False     False   False     False   
19     False  False  False      False   False     False   False     False   
20     False  False  False      False   False     False   False     False   
21     False  False  False      False   False     False   False     False   
22     False  False  False      False   False     False   False     False   
23     False  False  False      False   False     False   False     False   
24     False  False  False      False   False     False   False     False   
25     False  False  False      False   False     False   False     False   
26     False  False  False      False   False     False   False     False   
27     False  False  False      False   False     False   False     False   
28     False  False  False      False   False     False   False     False   
29     False  False  False      False   False     False   False     False   
30     False  False  False      False   False     False   False     False   
31     False  False  False      False   False     False   False     False   
32     False  False  False      False   False     False   False     False   
33     False  False  False      False   False     False   False     False   
34     False  False  False      False   False     False   False     False   
35     False  False  False      False   False     False   False     False   
36     False  False  False      False   False     False   False     False   
37     False  False  False      False   False     False   False     False   
38     False  False  False      False   False     False   False     False   
39     False  False  False      False   False     False   False     False   

    estado_pago  
0         False  
1         False  
2         False  
3         False  
4         False  
5         False  
6         False  
7         False  
8         False  
9         False  
10        False  
11        False  
12        False  
13        False  
14        False  
15        False  
16        False  
17        False  
18        False  
19        False  
20        False  
21        False  
22        False  
23        False  
24        False  
25        False  
26        False  
27        False  
28        False  
29        False  
30        False  
31        False  
32        False  
33        False  
34        False  
35        False  
36        False  
37        False  
38        False  
39        False

In [ ]:
# Contar nulos por columna

df.isnull().sum()

id_venta       0
fecha          0
curso          0
categoria      0
precio         1
cantidad       0
region         0
vendedor       0
estado_pago    0
dtype: int64

In [ ]:
# Filtrar filas con nulos

df[df.isnull().any(axis=1)]

# En columna cantidad = "NULL" (string literal, texto). Esta NO es nula para Pandas.

id_venta      fecha                curso   categoria   precio  cantidad  \
10        11 2024-02-10         Data Science  Tecnología      NaN       1.0   
17        18 2024-03-06  Atención al cliente      Ventas  15000.0       NaN   

    region     vendedor estado_pago  
10  Centro  No asignado      Pagado  
17  Centro        Pedro      Pagado

In [ ]:
# Detectar las filas con NaN reales y las filas con texto raro

valores_raros = ["", " ", "-", "NA", "N/A", "null", "NULL", "None", None]

df[ df.isin(valores_raros).any(axis=1) | df.isnull().any(axis=1) ]

# Pero SÍ aparece si vos buscás strings raros:

id_venta      fecha                curso   categoria   precio cantidad  \
10        11 2024-02-10         Data Science  Tecnología      NaN        1   
17        18 2024-03-06  Atención al cliente      Ventas  15000.0     NULL   

    region     vendedor estado_pago  
10  Centro  No asignado      Pagado  
17  Centro        Pedro      Pagado

In [ ]:
# Si querés que "NULL" de cantidad pase a ser NaN para unificar:
df = df.replace(["NULL", "null", "None", "-", ""], np.nan)

In [ ]:
# Eliminar filas con nulos
df_sin_nulos = df.dropna()

In [ ]:
# Identificar duplicados

df.duplicated().head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
# Ver solo duplicados

df[df.duplicated()]

Empty DataFrame
Columns: [id_venta, fecha, curso, categoria, precio, cantidad, region, vendedor, estado_pago]
Index: []

In [ ]:
# Eliminar duplicados (conservar solo el primero)

df_sin_dups = df.drop_duplicates()

In [ ]:
# Eliminar duplicados de una columna específica

df_sin_dups_curso = df.drop_duplicates(subset="curso")

In [ ]:
# Reemplazo de valores

df["curso"] = df["curso"].replace({
    "marketing": "Marketing",
    "Marketing ": "Marketing"
})

df["precio"] = df["precio"].replace("0", "20000")

In [ ]:
# Renombrado de columnas e índices

df = df.rename(columns={"precio": "precio_ars", "curso": "nombre_curso"})

In [ ]:
# Renombrar indice

df = df.rename(index={0: "venta_1"})

In [ ]:
# Conversión de tipos

# Convertir a numérico
df["precio_ars"] = pd.to_numeric(df["precio_ars"], errors="coerce")

# Convertir a fecha
df["fecha"] = pd.to_datetime(df["fecha"], errors="coerce")

# Convertir a string
df["nombre_curso"] = df["nombre_curso"].astype(str)

In [ ]:
# Correción de texto

df["nombre_curso"] = (
    df["nombre_curso"]
    .str.lower()          # 1) Convierte todo a minúsculas
    .str.strip()          # 2) Quita espacios al inicio y al final
    .str.replace("  ", " ", regex=False)  # 3) Reemplaza dobles espacios por un espacio
)

In [ ]:
# Identificación básica de outliers: Se usa para encontrar valores anómalos

Q1 = df["precio_ars"].quantile(0.25)
Q3 = df["precio_ars"].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df["precio_ars"] < Q1 - 1.5*IQR) | (df["precio_ars"] > Q3 + 1.5*IQR)]
outliers

# Si esta vacio Significa que NO HAY outliers según la regla del IQR. NO quiere decir que tus datos no tengan errores.
# Solo significa que según esta regla estadística, todos tus precios están dentro del rango esperado.


Empty DataFrame
Columns: [id_venta, fecha, nombre_curso, categoria, precio_ars, cantidad, region, vendedor, estado_pago]
Index: []

In [ ]:
# Normalización y escalado básico → Para Machine Learning, Para comparar valores en la misma escala, Para gráficos donde querés evitar escalas enormes, Para algoritmos que usan distancias (k-means, regresión, redes, KNN)

#Normalizar precios entre 0 y 1:

# df["precio_norm"] = (df["precio"] - df["precio"].min()) / (df["precio"].max() - df["precio"].min())


# Escalado simple: Reduce la magnitud de los precios simplemente dividiendo todo por 1000.

# df["precio_scaled"] = df["precio"] / 1000


#### Operaciones con columnas y filas

In [ ]:
# Ordenar por columna (por defecto es ascendente, si queremos descendente ponemos ascending = False)
# inplace=True > actualiza el df, los cambios se guardan

df.sort_values("precio_ars", ascending=False, inplace=True)
df.head()

id_venta      fecha             nombre_curso   categoria  precio_ars  \
16        17 2024-03-05   estrategia empresarial    Negocios     35000.0   
26        27 2024-03-22  inteligencia artificial  Tecnología     34000.0   
24        25 2024-03-20   transformación digital  Tecnología     33000.0   
25        26 2024-03-21                okr y kpi  Tecnología     31000.0   
2          3 2024-01-08             data science  Tecnología     30000.0   

    cantidad  region vendedor estado_pago  
16       1.0     Sur     Lara      Pagado  
26       1.0     Sur     Lara      Pagado  
24       1.0    Cuyo     Luis      Pagado  
25       1.0  Centro    Pedro      Pagado  
2        1.0     Sur      Ana      Pagado

In [ ]:
# Ordenar por múltiples columnas

df.sort_values(["nombre_curso", "precio_ars"]).head()

id_venta      fecha           nombre_curso     categoria  precio_ars  \
27        28 2024-03-25    análisis de mercado      Negocios     28000.0   
28        29 2024-03-28    análisis de mercado      NEGOCIOS     28000.0   
17        18 2024-03-06    atención al cliente        Ventas     15000.0   
18        19 2024-03-07    atención al cliente        Ventas     15000.0   
13        14 2024-02-15  comunicación efectiva  comunicación     16000.0   

    cantidad  region vendedor estado_pago  
27       1.0   Norte    Sofía      Pagado  
28       2.0   Norte    Sofía      Pagado  
17       NaN  Centro    Pedro      Pagado  
18       1.0  Centro    Pedro      Pagado  
13       1.0     Sur      Ana      Pagado

In [ ]:
# Ordenar por indice

df = df.reset_index(drop=True) # Reset the index to numerical values to avoid mixed types (ya que sa había cambiado 0 por venta_1)
df.sort_index().head()

id_venta      fecha  nombre_curso   categoria  precio_ars  cantidad  \
0         1 2024-01-03     marketing   Marketing     20000.0       1.0   
1         2 2024-01-05      finanzas    Finanzas     25000.0       1.0   
2         3 2024-01-08  data science  Tecnología     30000.0       1.0   
3         4 2024-01-09  data science  tecnología     30000.0       2.0   
4         5 2024-01-15     liderazgo   Liderazgo     28000.0       1.0   

   region vendedor estado_pago  
0   Norte      Ana      Pagado  
1   Norte     Luis   Pendiente  
2     Sur      Ana      Pagado  
3     Sur      Ana      Pagado  
4  Centro    Sofía      Pagado

In [ ]:
# Creación de nuevas columnas

df["ingreso_total"] = df["precio_ars"] * df["cantidad"]

df["precio_desc_10"] = df["precio_ars"] * 0.90

df["rango_precio"] = df["precio_ars"].apply(lambda x: "Alto" if x > 20000 else "Bajo")

In [ ]:
# Eliminación de columnas o filas
# drop() elimina columnas o filas sin modificar el DataFrame original, a menos que uses inplace=True.
# axis=1 → columnas
# axis=0 → filas

df = df.drop(columns=["precio_desc_10"]) #Elimina columna precio_desc_10

# df = df.drop(index=[2, 4]) → Eliminar filas por índice

In [ ]:
# Filtrado condicional → & → AND // | → OR // ~ → NOT

#df[df["precio_ars"] > 18000] #Precio mayor a 18.000
df[(df["precio_ars"] > 18000) & (df["categoria"] == "Negocios")] #cursos caros y categoría Negocios
#df[(df["nombre_curso"] == "Marketing") | (df["nombre_curso"] == "Python")] #Marketing o Python
#df[~(df["nombre_curso"] == "Marketing")] #todo menos Marketing

# solo muestra el úlitmo, salvo que se ponga print a todos o ejecuten por celda de código separado

id_venta      fecha            nombre_curso categoria  precio_ars  \
16        17 2024-03-05  estrategia empresarial  Negocios     35000.0   
27        28 2024-03-25     análisis de mercado  Negocios     28000.0   
15        16 2024-03-01          emprendimiento  Negocios     23000.0   
38        39 2024-04-15          emprendimiento  Negocios     23000.0   

    cantidad  region vendedor estado_pago  ingreso_total rango_precio  
16       1.0     Sur     Lara      Pagado        35000.0         Alto  
27       1.0   Norte    Sofía      Pagado        28000.0         Alto  
15       1.0   Norte    Sofía   Pendiente        23000.0         Alto  
38       1.0  Centro    Pedro      Pagado        23000.0         Alto

In [ ]:
# Reindexación (reindex)

# Para:
# cambiar el orden de las filas,
# agregar o quitar índices,
# reordenar para unir DataFrames.
# Si un índice no existe, Pandas pone un NaN.

nuevo_orden = [3, 0, 2, 1, 4]
df.reindex(nuevo_orden)

id_venta      fecha  nombre_curso   categoria  precio_ars  cantidad  \
3         4 2024-01-09  data science  tecnología     30000.0       2.0   
0         1 2024-01-03     marketing   Marketing     20000.0       1.0   
2         3 2024-01-08  data science  Tecnología     30000.0       1.0   
1         2 2024-01-05      finanzas    Finanzas     25000.0       1.0   
4         5 2024-01-15     liderazgo   Liderazgo     28000.0       1.0   

   region vendedor estado_pago  ingreso_total rango_precio  
3     Sur      Ana      Pagado        60000.0         Alto  
0   Norte      Ana      Pagado        20000.0         Bajo  
2     Sur      Ana      Pagado        30000.0         Alto  
1   Norte     Luis   Pendiente        25000.0         Alto  
4  Centro    Sofía      Pagado        28000.0         Alto

In [ ]:
# Otras funciones útiles

# apply() → Aplicar una función a una columna completa (Logica personalizada (if, cálculos, limpieza))
# applymap() → Aplicar una función a cada valor de toda la tabla (Conversión global de formatos)
# map() → Reemplazar valores rápidamente en una columna (Traducir categorías)


In [ ]:
# Agrupar datos → groupby() divide el DataFrame en grupos y permite aplicar agregaciones.
df.groupby("nombre_curso")["ingreso_total"].sum()

nombre_curso
análisis de mercado         84000.0
atención al cliente         15000.0
comunicación efectiva       32000.0
copywriting                 20000.0
data science               120000.0
emprendimiento              69000.0
estrategia empresarial      35000.0
excel para negocios         36000.0
finanzas                    25000.0
google ads                  46000.0
inteligencia artificial     34000.0
liderazgo                   56000.0
marketing                   80000.0
negociación                 24000.0
okr y kpi                   31000.0
power bi                    54000.0
recursos humanos            22000.0
redes sociales              42000.0
rrhh                        44000.0
seo                         25000.0
transformación digital      33000.0
ventas                     147000.0
Name: ingreso_total, dtype: float64

In [ ]:
# Agregaciones múltiples → agg() permite aplicar varias funciones al mismo tiempo sobre un grupo. Muy útil para KPIs por producto

df.groupby("nombre_curso").agg({
    "precio_ars": ["mean", "max", "min"],
    "cantidad": "sum",
    "ingreso_total": "sum"
})

precio_ars                   cantidad ingreso_total
                              mean      max      min      sum           sum
nombre_curso                                                               
análisis de mercado        28000.0  28000.0  28000.0      3.0       84000.0
atención al cliente        15000.0  15000.0  15000.0      1.0       15000.0
comunicación efectiva      16000.0  16000.0  16000.0      2.0       32000.0
copywriting                20000.0  20000.0  20000.0      1.0       20000.0
data science               30000.0  30000.0  30000.0      5.0      120000.0
emprendimiento             23000.0  23000.0  23000.0      3.0       69000.0
estrategia empresarial     35000.0  35000.0  35000.0      1.0       35000.0
excel para negocios        18000.0  18000.0  18000.0      2.0       36000.0
finanzas                   25000.0  25000.0  25000.0      1.0       25000.0
google ads                 23000.0  23000.0  23000.0      2.0       46000.0
inteligencia artificial    34000.0  34000.0  34000.0      1.0       34000.0
liderazgo                  28000.0  28000.0  28000.0      2.0       56000.0
marketing                  20000.0  20000.0  20000.0      4.0       80000.0
negociación                24000.0  24000.0  24000.0      1.0       24000.0
okr y kpi                  31000.0  31000.0  31000.0      1.0       31000.0
power bi                   27000.0  27000.0  27000.0      2.0       54000.0
recursos humanos           22000.0  22000.0  22000.0      1.0       22000.0
redes sociales             21000.0  21000.0  21000.0      2.0       42000.0
rrhh                       22000.0  22000.0  22000.0      2.0       44000.0
seo                        25000.0  25000.0  25000.0      1.0       25000.0
transformación digital     33000.0  33000.0  33000.0      1.0       33000.0
ventas                     21000.0  21000.0  21000.0      7.0      147000.0

In [ ]:
# Agrupaciones múltiples (por mas de una columna)

df.groupby(["categoria", "nombre_curso"])["ingreso_total"].sum()

categoria     nombre_curso           
Comunicación  comunicación efectiva       16000.0
Finanzas      finanzas                    25000.0
Liderazgo     liderazgo                   56000.0
Marketing     copywriting                 20000.0
              google ads                  23000.0
              marketing                   80000.0
              redes sociales              42000.0
              seo                         25000.0
NEGOCIOS      análisis de mercado         56000.0
Negocios      análisis de mercado         28000.0
              emprendimiento              46000.0
              estrategia empresarial      35000.0
RRHH          recursos humanos            22000.0
              rrhh                        22000.0
Tecnología    data science                60000.0
              excel para negocios         36000.0
              inteligencia artificial     34000.0
              okr y kpi                   31000.0
              power bi                    54000.0
              transformación digital      33000.0
Ventas        atención al cliente         15000.0
              negociación                 24000.0
              ventas                     105000.0
comunicación  comunicación efectiva       16000.0
marketing     google ads                  23000.0
negocios      emprendimiento              23000.0
rrhh          rrhh                        22000.0
tecnología    data science                60000.0
ventas        ventas                      42000.0
Name: ingreso_total, dtype: float64

In [ ]:
# Transformaciones dentro de grupos (transform)
# A diferencia de groupby() que reduce, transform() devuelve algo del mismo tamaño que el DataFrame.

df["prom_categoria"] = df.groupby("categoria")["precio_ars"].transform("mean")
df.head()

# Cada fila tiene el precio promedio de su categoría.

id_venta      fecha             nombre_curso   categoria  precio_ars  \
16        17 2024-03-05   estrategia empresarial    Negocios     35000.0   
26        27 2024-03-22  inteligencia artificial  Tecnología     34000.0   
24        25 2024-03-20   transformación digital  Tecnología     33000.0   
25        26 2024-03-21                okr y kpi  Tecnología     31000.0   
2          3 2024-01-08             data science  Tecnología     30000.0   

    cantidad  region vendedor estado_pago  ingreso_total rango_precio  \
16       1.0     Sur     Lara      Pagado        35000.0         Alto   
26       1.0     Sur     Lara      Pagado        34000.0         Alto   
24       1.0    Cuyo     Luis      Pagado        33000.0         Alto   
25       1.0  Centro    Pedro      Pagado        31000.0         Alto   
2        1.0     Sur      Ana      Pagado        30000.0         Alto   

    prom_categoria  
16    27250.000000  
26    27555.555556  
24    27555.555556  
25    27555.555556  
2     27555.555556

In [ ]:
# Tablas dinámicas (pivot table) → funcionan como Excel pero con más flexibilidad

#Filas (index)
#Columnas (columns)
#Valores agregados (values)
#Función (aggfunc)

pd.pivot_table(
    df,
    values="ingreso_total",
    index="categoria",
    columns="estado_pago",
    aggfunc="sum"
)

/tmp/ipython-input-2183964834.py:8: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(


estado_pago     Pagado  Pendiente
categoria                        
Comunicación   16000.0        0.0
Finanzas           0.0    25000.0
Liderazgo      28000.0    28000.0
Marketing     148000.0    42000.0
NEGOCIOS       56000.0        0.0
Negocios       86000.0    23000.0
RRHH           44000.0        0.0
Tecnología    221000.0    27000.0
Ventas        144000.0        0.0
comunicación   16000.0        0.0
marketing      23000.0        0.0
negocios       23000.0        0.0
rrhh           22000.0        0.0
tecnología     60000.0        0.0
ventas         42000.0        0.0

In [ ]:
# Cruces de datos (crosstab) → genera tablas de frecuencia.
# Útil para: cantidad de cursos por categoría, recuentos de inscripciones por tipo, análisis exploratorio rápido.

pd.crosstab(df["categoria"], df["nombre_curso"])

nombre_curso  análisis de mercado  atención al cliente  comunicación efectiva  \
categoria                                                                       
Comunicación                    0                    0                      1   
Finanzas                        0                    0                      0   
Liderazgo                       0                    0                      0   
Marketing                       0                    0                      0   
NEGOCIOS                        1                    0                      0   
Negocios                        1                    0                      0   
RRHH                            0                    0                      0   
Tecnología                      0                    0                      0   
Ventas                          0                    2                      0   
comunicación                    0                    0                      1   
marketing                       0                    0                      0   
negocios                        0                    0                      0   
rrhh                            0                    0                      0   
tecnología                      0                    0                      0   
ventas                          0                    0                      0   

nombre_curso  copywriting  data science  emprendimiento  \
categoria                                                 
Comunicación            0             0               0   
Finanzas                0             0               0   
Liderazgo               0             0               0   
Marketing               1             0               0   
NEGOCIOS                0             0               0   
Negocios                0             0               2   
RRHH                    0             0               0   
Tecnología              0             3               0   
Ventas                  0             0               0   
comunicación            0             0               0   
marketing               0             0               0   
negocios                0             0               1   
rrhh                    0             0               0   
tecnología              0             1               0   
ventas                  0             0               0   

nombre_curso  estrategia empresarial  excel para negocios  finanzas  \
categoria                                                             
Comunicación                       0                    0         0   
Finanzas                           0                    0         1   
Liderazgo                          0                    0         0   
Marketing                          0                    0         0   
NEGOCIOS                           0                    0         0   
Negocios                           1                    0         0   
RRHH                               0                    0         0   
Tecnología                         0                    2         0   
Ventas                             0                    0         0   
comunicación                       0                    0         0   
marketing                          0                    0         0   
negocios                           0                    0         0   
rrhh                               0                    0         0   
tecnología                         0                    0         0   
ventas                             0                    0         0   

nombre_curso  google ads  ...  marketing  negociación  okr y kpi  power bi  \
categoria                 ...                                                
Comunicación           0  ...          0            0          0         0   
Finanzas               0  ...          0            0          0         0   
Liderazgo              0  ...          0            0          0         0   
Marketing           

In [ ]:
df.head()

id_venta      fecha             nombre_curso   categoria  precio_ars  \
16        17 2024-03-05   estrategia empresarial    Negocios     35000.0   
26        27 2024-03-22  inteligencia artificial  Tecnología     34000.0   
24        25 2024-03-20   transformación digital  Tecnología     33000.0   
25        26 2024-03-21                okr y kpi  Tecnología     31000.0   
2          3 2024-01-08             data science  Tecnología     30000.0   

    cantidad  region vendedor estado_pago  ingreso_total rango_precio  \
16       1.0     Sur     Lara      Pagado        35000.0         Alto   
26       1.0     Sur     Lara      Pagado        34000.0         Alto   
24       1.0    Cuyo     Luis      Pagado        33000.0         Alto   
25       1.0  Centro    Pedro      Pagado        31000.0         Alto   
2        1.0     Sur      Ana      Pagado        30000.0         Alto   

    prom_categoria  
16    27250.000000  
26    27555.555556  
24    27555.555556  
25    27555.555556  
2     27555.555556

#### Combinación y unión de DataFrames

##### Concatenación con pd.concat()

Dos formas principales:

1) Vertical (una tabla arriba de otra)

Igual que agregar filas.

Requiere que las columnas coincidan (o crea NaN en las faltantes).

2) Horizontal (una tabla al lado de otra)

Une por el índice (como coser columnas).

⚠️ Importante:

No elimina duplicados.

No detecta claves repetidas.

Ideal para unir “bases del mismo tipo” (ej: ventas de distintos meses

In [ ]:
# Vertical

ventas_enero = pd.DataFrame({
    "id_venta": [1, 2],
    "curso": ["Marketing", "Python"],
    "precio": [20000, 25000]
})

ventas_febrero = pd.DataFrame({
    "id_venta": [3, 4],
    "curso": ["Excel", "Liderazgo"],
    "precio": [18000, 30000]
})

ventas_total = pd.concat([ventas_enero, ventas_febrero], ignore_index=True)
ventas_total

id_venta      curso  precio
0         1  Marketing   20000
1         2     Python   25000
2         3      Excel   18000
3         4  Liderazgo   30000

In [ ]:
# Horizontal

df_info = pd.DataFrame({"categoria": ["Negocios", "Tech"]})
df_pre = pd.DataFrame({"nivel": ["Premium", "Base"]})

df_concat = pd.concat([df_info, df_pre], axis=1)
df_concat

categoria    nivel
0  Negocios  Premium
1      Tech     Base

##### Uniones tipo SQL con merge()

merge() funciona igual que las uniones SQL:

- inner	→ Solo coincidencias

- left → 	Todo el izquierdo + coincidencias

- right	→ Todo el derecho + coincidencias

- outer	→ Todo de ambos, con NaN donde falte

Claves para unir:

- on — cuando las columnas tienen el MISMO nombre en ambos DataFrames

- left_on / right_on — cuando los nombres NO coinciden

- index — unir por índice

In [ ]:
clientes = pd.DataFrame({
    "id_cliente": [1, 2, 3],
    "nombre": ["Ana", "Luis", "María"]
})

ventas = pd.DataFrame({
    "id_venta": [101, 102, 103, 104],
    "id_cliente": [1, 1, 2, 4],
    "curso": ["Marketing", "Python", "Excel", "Liderazgo"]
})

In [ ]:
#inner join

# Solo clientes con ventas

df_inner = clientes.merge(ventas, on="id_cliente", how="inner")
df_inner

id_cliente nombre  id_venta      curso
0           1    Ana       101  Marketing
1           1    Ana       102     Python
2           2   Luis       103      Excel

In [ ]:
# Left Join

# Todos los clientes, aunque no tengan ventas

df_left = clientes.merge(ventas, on="id_cliente", how="left")
df_left

id_cliente nombre  id_venta      curso
0           1    Ana     101.0  Marketing
1           1    Ana     102.0     Python
2           2   Luis     103.0      Excel
3           3  María       NaN        NaN

In [ ]:
# Right Join

# todas las ventas, aunque no tengan cliente

df_right = clientes.merge(ventas, on="id_cliente", how="right")
df_right

id_cliente nombre  id_venta      curso
0           1    Ana       101  Marketing
1           1    Ana       102     Python
2           2   Luis       103      Excel
3           4    NaN       104  Liderazgo

In [ ]:
# Outer Join

# Todo, absolutamente todo

df_outer = clientes.merge(ventas, on="id_cliente", how="outer")
df_outer

id_cliente nombre  id_venta      curso
0           1    Ana     101.0  Marketing
1           1    Ana     102.0     Python
2           2   Luis     103.0      Excel
3           3  María       NaN        NaN
4           4    NaN     104.0  Liderazgo

In [ ]:
# left_on / right_on → cuando las columnas NO tienen el mismo nombre

regiones = pd.DataFrame({
    "cliente_id": [1, 2, 3, 4],
    "region": ["CABA", "Norte", "Sur", "Cuyo"]
})

clientes_reg = clientes.merge(
    regiones,
    left_on="id_cliente",
    right_on="cliente_id",
    how="left"
)

clientes_reg

id_cliente nombre  cliente_id region
0           1    Ana           1   CABA
1           2   Luis           2  Norte
2           3  María           3    Sur

In [ ]:
# Uniones basadas en indices (usando el indice como clave)

ventas_por_indice = ventas.set_index("id_cliente")

clientes_join = clientes.merge(
    ventas_por_indice,
    left_on="id_cliente",
    right_index=True,
    how="left"
)

clientes_join

id_cliente nombre  id_venta      curso
0           1    Ana     101.0  Marketing
0           1    Ana     102.0     Python
1           2   Luis     103.0      Excel
2           3  María       NaN        NaN

In [ ]:
# Unión jerárquica → permiten merges más complejos (cuando hay múltiples claves o cuando la tabla tiene MultiIndex.)

df1 = pd.DataFrame({
    "categoria": ["Negocios", "Negocios", "Tech"],
    "curso": ["Marketing", "Ventas", "Python"],
    "precio": [20000, 25000, 30000]
})

df2 = pd.DataFrame({
    "categoria": ["Negocios", "Tech"],
    "curso": ["Marketing", "Python"],
    "instructor": ["Ana", "Luis"]
})

df_multi = df1.merge(df2, on=["categoria", "curso"], how="left")

df_multi

categoria      curso  precio instructor
0  Negocios  Marketing   20000        Ana
1  Negocios     Ventas   25000        NaN
2      Tech     Python   30000       Luis

In [ ]:
import pandas as pd

# Manejo de duplicados en uniones

# Cuando una clave aparece varias veces en ambos DataFrames, se genera un producto cartesiano. Ejemplo: un cliente con varias compras
# Pandas te devuelve todas las combinaciones posibles.

a = pd.DataFrame({"id": [1,1], "curso": ["Mkt A", "Mkt B"]})
b = pd.DataFrame({"id": [1,1], "instructor": ["Ana", "Luis"]})

pd.merge(a, b, on="id", how="inner")

id  curso instructor
0   1  Mkt A        Ana
1   1  Mkt A       Luis
2   1  Mkt B        Ana
3   1  Mkt B       Luis

#### Reestructuración de DataFrames (Reshaping)

Pasar de ancho a largo (melt) o Pasar de largo a ancho (pivot) → trabajan con columnas

Crear tablas dinámicas (pivot_table)

Trabajar con índices jerárquicos (MultiIndex)

Aplanar o compactar niveles (stack / unstack) → trabajan con índices

In [ ]:
# melt() — pasar de formato ANCHO a LARGO

df = pd.DataFrame({
    "region": ["CABA", "Norte", "Sur"], #columna1
    "enero": [100, 80, 60],             #columna2
    "febrero": [120, 90, 70],           #columna3
    "marzo": [130, 100, 75]             #columna4
})


df_largo = df.melt(
    id_vars="region",        #columna1
    var_name="mes",          #columna2
    value_name="ventas"      #columna3
)

df_largo

region      mes  ventas
0   CABA    enero     100
1  Norte    enero      80
2    Sur    enero      60
3   CABA  febrero     120
4  Norte  febrero      90
5    Sur  febrero      70
6   CABA    marzo     130
7  Norte    marzo     100
8    Sur    marzo      75

In [ ]:
# pivot() — pasar de LARGO a ANCHO

# Funciona bien si: NO hay duplicados en el índice de pivoteo y Cada combinación es única

df_ancho = df_largo.pivot(
    index="region",
    columns="mes",
    values="ventas"
)

df_ancho

mes     enero  febrero  marzo
region                       
CABA      100      120    130
Norte      80       90    100
Sur        60       70     75

In [ ]:
# pivot_table() — Tabla dinámica (tipo Excel)

# pivot() falla si hay duplicados. pivot_table() no falla porque permite agregaciones (sum, mean, count, etc.)

# Ejemplo — ventas por curso y región

ventas = pd.DataFrame({
    "region": ["CABA","CABA","Norte","Sur","Sur"],
    "curso": ["Marketing","Excel","Marketing","Excel","Excel"],
    "precio": [20000,15000,22000,18000,18000]
})

tabla = pd.pivot_table(
    ventas,
    values="precio",
    index="region",
    columns="curso",
    aggfunc="mean",
    fill_value=0
)

tabla

curso     Excel  Marketing
region                    
CABA    15000.0    20000.0
Norte       0.0    22000.0
Sur     18000.0        0.0

In [ ]:
# MultiIndex — Índices jerárquicos (en filas o columnas)

# Sirve para: agrupar niveles (ej: región + curso), manejar datos por jerarquías, resumir información compleja

df_multi = ventas.set_index(["region", "curso"])
df_multi

precio
region curso            
CABA   Marketing   20000
       Excel       15000
Norte  Marketing   22000
Sur    Excel       18000
       Excel       18000

In [ ]:
# sort_index(level=...) — ordenar por niveles

df_multi.sort_index(level=0)     # Ordena por región
df_multi.sort_index(level=1)     # Ordena por curso

precio
region curso            
CABA   Excel       15000
Sur    Excel       18000
       Excel       18000
CABA   Marketing   20000
Norte  Marketing   22000

In [ ]:
# stack() — Columnas → Filas

# Compacta columnas
# Convierte columnas en un nivel de índice

df = pd.DataFrame({
    "curso": ["Marketing", "Python", "Ventas"], #columna1
    "precio_2023": [15000, 20000, 17000],       #columna2
    "precio_2024": [18000, 22000, 19000]        #columna3
})


df_indexed = df.set_index("curso")

df_stacked = df_indexed.stack()

df_stacked

curso                 
Marketing  precio_2023    15000
           precio_2024    18000
Python     precio_2023    20000
           precio_2024    22000
Ventas     precio_2023    17000
           precio_2024    19000
dtype: int64

In [ ]:
# unstack() — Filas → Columnas

df_unstacked = df_stacked.unstack()
df_unstacked

precio_2023  precio_2024
curso                              
Marketing        15000        18000
Python           20000        22000
Ventas           17000        19000

In [ ]:
print("Shape original:", df.shape)
print("Shape stack:", df_stacked.shape)
print("Shape unstack:", df_unstacked.shape)

Shape original: (3, 3)
Shape stack: (6,)
Shape unstack: (3, 2)


#### Manejo de fecha y tiempos

Pandas tiene un tipo especial: datetime64, que permite:

- ordenar por fechas

- filtrar rangos

- sumar/restar días

- re-samplear (agrupar por mes, semana, año)

- calcular diferencias (lag, diff)

- extraer año/mes/día

- trabajar con índices de tiempo

In [ ]:
# Convertir columna a datetime

df = pd.DataFrame({
    "fecha": ["2024-01-03", "2024-01-05", "2024-02-10", "2024-02-15"],
    "curso": ["Marketing", "Python", "Marketing", "Finanzas"],
    "ventas": [5, 12, 8, 10]
})

df["fecha"] = pd.to_datetime(df["fecha"])
df

fecha      curso  ventas
0 2024-01-03  Marketing       5
1 2024-01-05     Python      12
2 2024-02-10  Marketing       8
3 2024-02-15   Finanzas      10

In [ ]:
# Acceder a componentes .dt

# Una vez que la fecha es datetime, podés extraer partes:

df["anio"] = df["fecha"].dt.year
df["mes"] = df["fecha"].dt.month
df["dia"] = df["fecha"].dt.day
df["nombre_mes"] = df["fecha"].dt.month_name()
df

fecha      curso  ventas  anio  mes  dia nombre_mes
0 2024-01-03  Marketing       5  2024    1    3    January
1 2024-01-05     Python      12  2024    1    5    January
2 2024-02-10  Marketing       8  2024    2   10   February
3 2024-02-15   Finanzas      10  2024    2   15   February

In [ ]:
# Filtrar por rangos de fecha

df[df["fecha"] >= "2024-02-01"]


fecha      curso  ventas  anio  mes  dia nombre_mes
2 2024-02-10  Marketing       8  2024    2   10   February
3 2024-02-15   Finanzas      10  2024    2   15   February

In [ ]:
# Ordenar por fechas

df.sort_values("fecha")


fecha      curso  ventas  anio  mes  dia nombre_mes
0 2024-01-03  Marketing       5  2024    1    3    January
1 2024-01-05     Python      12  2024    1    5    January
2 2024-02-10  Marketing       8  2024    2   10   February
3 2024-02-15   Finanzas      10  2024    2   15   February

In [ ]:
# Usar fecha como índice (DatetimeIndex)

df = df.set_index("fecha")

df["2024-01-01":"2024-01-31"]


curso  ventas  anio  mes  dia nombre_mes
fecha                                                   
2024-01-03  Marketing       5  2024    1    3    January
2024-01-05     Python      12  2024    1    5    January

In [ ]:
# Re-sampling (agrupar por períodos)

# "D" → día
# "W" → semana
# "M" → mes
# "Q" → trimestre
# "Y" → año

# ventas por mes
df.resample("M")["ventas"].sum()
# ventas promedio por semana
df.resample("W")["ventas"].mean()

/tmp/ipython-input-1033150713.py:10: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample("M")["ventas"].sum()


fecha
2024-01-07     8.5
2024-01-14     NaN
2024-01-21     NaN
2024-01-28     NaN
2024-02-04     NaN
2024-02-11     8.0
2024-02-18    10.0
Freq: W-SUN, Name: ventas, dtype: float64

In [ ]:
# Calcular diferencias: diff(), pct_change(), shift()

# shift() desplaza la serie
# diff() calcula diferencia con el dato anterior
# pct_change() da cambio porcentual

df["ventas_lag1"] = df["ventas"].shift(1)
df["dif_dia"] = df["ventas"].diff()
df["variacion_pct"] = df["ventas"].pct_change()

df

curso  ventas  anio  mes  dia nombre_mes  ventas_lag1  \
fecha                                                                   
2024-01-03  Marketing       5  2024    1    3    January          NaN   
2024-01-05     Python      12  2024    1    5    January          5.0   
2024-02-10  Marketing       8  2024    2   10   February         12.0   
2024-02-15   Finanzas      10  2024    2   15   February          8.0   

            dif_dia  variacion_pct  
fecha                               
2024-01-03      NaN            NaN  
2024-01-05      7.0       1.400000  
2024-02-10     -4.0      -0.333333  
2024-02-15      2.0       0.250000

In [ ]:
# Sumar/restar días (timedelta)

df["fecha_mas_7"] = df.index + pd.Timedelta(days=7)

df["fecha_menos_1mes"] = df.index - pd.DateOffset(months=1)

df[['fecha_mas_7',"fecha_menos_1mes"]]

fecha_mas_7 fecha_menos_1mes
fecha                                  
2024-01-03  2024-01-10       2023-12-03
2024-01-05  2024-01-12       2023-12-05
2024-02-10  2024-02-17       2024-01-10
2024-02-15  2024-02-22       2024-01-15

In [ ]:
# Agrupar por año/mes usando datetime directamente

df.groupby(df.index.month)["ventas"].sum()

fecha
1    17
2    18
Name: ventas, dtype: int64